#!/bin/bash

#SBATCH --job-name d2q9-bgk
#SBATCH --nodes 4
#SBATCH --ntasks-per-node 1
#SBATCH --time 00:15:00
#SBATCH --partition teaching
#SBATCH --output d2q9-bgk.out

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`

#! Run the executable
mpirun ./d2q9-bgk -np 1 input_128x128.params obstacles_1024x1024.dat
mpirun ./d2q9-bgk -np 14 input_128x128.params obstacles_1024x1024.dat
mpirun ./d2q9-bgk -np 28 input_128x128.params obstacles_1024x1024.dat
mpirun ./d2q9-bgk -np 42 input_128x128.params obstacles_1024x1024.dat
mpirun ./d2q9-bgk -np 56 input_128x128.params obstacles_1024x1024.dat
mpirun ./d2q9-bgk -np 70 input_128x128.params obstacles_1024x1024.dat
mpirun ./d2q9-bgk -np 84 input_128x128.params obstacles_1024x1024.dat
mpirun ./d2q9-bgk -np 98 input_128x128.params obstacles_1024x1024.dat
mpirun ./d2q9-bgk -np 112 input_128x128.params obstacles_1024x1024.dat
